# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RRChat' do
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'MJRefresh', '~> 3.1.12'
end
